// src/components/edges/ImageRoleEdge.vue
<template>
  <!-- Custom edge with image role selector | 带图片角色选择器的自定义边 -->
  <BaseEdge :path="path" :style="edgeStyle" />
  
  <!-- Edge label with role dropdown | 带角色下拉的边标签 -->
  <EdgeLabelRenderer>
    <div 
      :style="{ 
        position: 'absolute', 
        transform: `translate(-50%, -50%) translate(${labelX}px, ${labelY}px)`,
        pointerEvents: 'all'
      }"
      class="nodrag nopan"
    >
      <n-dropdown 
        :options="imageRoleOptions" 
        @select="handleRoleSelect"
        size="small"
      >
        <button 
          class="flex items-center gap-1 text-xs px-2 py-1 rounded-full bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-600 shadow-sm hover:shadow transition-shadow"
        >
          {{ currentRoleLabel }}
          <n-icon :size="10"><ChevronDownOutline /></n-icon>
        </button>
      </n-dropdown>
    </div>
  </EdgeLabelRenderer>
</template>

<script setup>
import { computed } from 'vue'
import { BaseEdge, EdgeLabelRenderer, getBezierPath } from '@vue-flow/core'
import { NDropdown, NIcon } from 'naive-ui'
import { ChevronDownOutline } from '@vicons/ionicons5'
import { edges, updateEdge } from '../../stores/canvas'

const props = defineProps({
  id: String,
  source: String,
  target: String,
  sourceX: Number,
  sourceY: Number,
  targetX: Number,
  targetY: Number,
  sourcePosition: String,
  targetPosition: String,
  data: Object,
  markerEnd: String,
  style: Object
})

// Image role options | 图片角色选项
const imageRoleOptions = [
  { label: '首帧', key: 'first_frame_image' },
  { label: '尾帧', key: 'last_frame_image' },
  { label: '参考图', key: 'input_reference' }
]

// Current role from edge data | 从边数据获取当前角色
const currentRole = computed(() => props.data?.imageRole || 'first_frame_image')

// Current role label | 当前角色标签
const currentRoleLabel = computed(() => {
  const option = imageRoleOptions.find(o => o.key === currentRole.value)
  return option?.label || '首帧'
})

// Calculate bezier path | 计算贝塞尔路径
const path = computed(() => {
  const [edgePath] = getBezierPath({
    sourceX: props.sourceX,
    sourceY: props.sourceY,
    targetX: props.targetX,
    targetY: props.targetY,
    sourcePosition: props.sourcePosition,
    targetPosition: props.targetPosition
  })
  return edgePath
})

// Label position (center of edge) | 标签位置（边的中心）
const labelX = computed(() => (props.sourceX + props.targetX) / 2)
const labelY = computed(() => (props.sourceY + props.targetY) / 2)

// Edge style | 边样式
const edgeStyle = computed(() => ({
  stroke: '#6366f1',
  strokeWidth: 2,
  ...props.style
}))

// Handle role selection | 处理角色选择
const handleRoleSelect = (role) => {
  // If selecting first_frame or last_frame, ensure uniqueness | 如果选择首帧或尾帧，确保唯一性
  if (role === 'first_frame_image' || role === 'last_frame_image') {
    // Find other edges connected to the same target with the same role | 查找连接到同一目标且具有相同角色的其他边
    const sameTargetEdges = edges.value.filter(edge =>
      edge.target === props.target &&
      edge.id !== props.id &&
      edge.data?.imageRole === role
    )

    // Auto-switch the other edge to the opposite role | 自动切换其他边到相反角色
    sameTargetEdges.forEach(edge => {
      const oppositeRole = role === 'first_frame_image' ? 'last_frame_image' : 'first_frame_image'
      updateEdge(edge.id, { imageRole: oppositeRole })
    })
  }

  // Update current edge role via store (triggers reactivity) | 通过 store 更新当前边角色（触发响应式）
  updateEdge(props.id, { imageRole: role })
}
</script>

// src/components/canvas/edges/ImageRoleEdge.tsx
/**
 * ImageRoleEdge - 自定义边组件
 * 用于 image → videoConfig 的连接，显示角色选择下拉菜单（首帧/尾帧/参考图）
 * 参考 Vue 版本 ImageRoleEdge.vue 实现
 */
import React, { memo, useState, useCallback, useMemo, useEffect, useRef } from 'react'
import {
  BaseEdge,
  EdgeLabelRenderer,
  getBezierPath,
  useReactFlow,
  type EdgeProps,
} from '@xyflow/react'
import { ChevronDown } from 'lucide-react'
import { useGraphStore } from '@/graph/store'

type ImageRole = 'first_frame_image' | 'last_frame_image' | 'input_reference'

interface ImageRoleEdgeData {
  imageRole?: ImageRole
  [key: string]: unknown
}

const IMAGE_ROLE_OPTIONS: { label: string; key: ImageRole }[] = [
  { label: '首帧', key: 'first_frame_image' },
  { label: '尾帧', key: 'last_frame_image' },
  { label: '参考图', key: 'input_reference' },
]

export const ImageRoleEdge = memo(function ImageRoleEdge({
  id,
  sourceX,
  sourceY,
  targetX,
  targetY,
  sourcePosition,
  targetPosition,
  data,
  selected,
}: EdgeProps) {
  const [showDropdown, setShowDropdown] = useState(false)
  const dropdownRef = useRef<HTMLDivElement>(null)
  const edgeData = data as ImageRoleEdgeData | undefined
  const { setEdges } = useReactFlow()

  // 计算贝塞尔路径
  const [edgePath, labelX, labelY] = getBezierPath({
    sourceX,
    sourceY,
    targetX,
    targetY,
    sourcePosition,
    targetPosition,
  })

  // 从 Zustand store 获取最新的角色数据
  const currentRole = useMemo(() => {
    // 首先从 props.data 获取
    if (edgeData?.imageRole) return edgeData.imageRole
    // 然后从 store 获取
    const storeEdge = useGraphStore.getState().edges.find(e => e.id === id)
    return (storeEdge?.data as any)?.imageRole || 'first_frame_image'
  }, [id, edgeData?.imageRole])

  // 当前角色标签
  const currentRoleLabel = useMemo(() => {
    const option = IMAGE_ROLE_OPTIONS.find((o) => o.key === currentRole)
    return option?.label || '首帧'
  }, [currentRole])

  // 点击外部关闭下拉菜单
  useEffect(() => {
    if (!showDropdown) return

    const handleClickOutside = (e: MouseEvent) => {
      if (dropdownRef.current && !dropdownRef.current.contains(e.target as Node)) {
        setShowDropdown(false)
      }
    }

    // 延迟添加监听，避免立即触发
    const timer = setTimeout(() => {
      document.addEventListener('mousedown', handleClickOutside)
    }, 10)

    return () => {
      clearTimeout(timer)
      document.removeEventListener('mousedown', handleClickOutside)
    }
  }, [showDropdown])

  // 处理角色选择
  const handleRoleSelect = useCallback(
    (role: ImageRole) => {
      // 1. 更新 Zustand store
      useGraphStore.getState().setEdgeImageRole(id, role)

      // 2. 同时更新 React Flow 的边数据（确保 UI 同步）
      setEdges((edges) =>
        edges.map((edge) => {
          if (edge.id === id) {
            return {
              ...edge,
              data: { ...edge.data, imageRole: role },
            }
          }
          return edge
        })
      )

      setShowDropdown(false)
    },
    [id, setEdges]
  )

  // 切换下拉菜单
  const toggleDropdown = useCallback((e: React.MouseEvent) => {
    e.stopPropagation()
    e.preventDefault()
    setShowDropdown((prev) => !prev)
  }, [])

  return (
    <>
      {/* 边线 */}
      <BaseEdge
        path={edgePath}
        style={{
          stroke: selected ? '#3b82f6' : '#6366f1',
          strokeWidth: selected ? 3 : 2,
        }}
      />

      {/* 边标签（角色选择器） */}
      <EdgeLabelRenderer>
        <div
          ref={dropdownRef}
          style={{
            position: 'absolute',
            transform: `translate(-50%, -50%) translate(${labelX}px, ${labelY}px)`,
            pointerEvents: 'all',
            zIndex: 1000,
          }}
          className="nodrag nopan"
        >
          {/* 角色按钮 */}
          <button
            onClick={toggleDropdown}
            onMouseDown={(e) => e.stopPropagation()}
            className={`
              flex items-center gap-1 text-xs px-2.5 py-1.5 rounded-full 
              bg-white dark:bg-gray-800 
              border border-gray-200 dark:border-gray-600 
              shadow-md hover:shadow-lg transition-shadow cursor-pointer
              ${selected ? 'ring-2 ring-blue-500' : ''}
            `}
          >
            <span className="text-gray-700 dark:text-gray-200 font-medium">{currentRoleLabel}</span>
            <ChevronDown size={12} className={`text-gray-500 transition-transform ${showDropdown ? 'rotate-180' : ''}`} />
          </button>

          {/* 下拉菜单 */}
          {showDropdown && (
            <div
              className="
                absolute top-full left-1/2 -translate-x-1/2 mt-2
                bg-white dark:bg-gray-800 
                border border-gray-200 dark:border-gray-600 
                rounded-lg shadow-xl overflow-hidden
                min-w-[90px]
              "
              style={{ zIndex: 9999 }}
              onMouseDown={(e) => e.stopPropagation()}
            >
              {IMAGE_ROLE_OPTIONS.map((option) => (
                <button
                  key={option.key}
                  onClick={(e) => {
                    e.stopPropagation()
                    e.preventDefault()
                    handleRoleSelect(option.key)
                  }}
                  onMouseDown={(e) => e.stopPropagation()}
                  className={`
                    w-full px-3 py-2 text-xs text-left
                    hover:bg-gray-100 dark:hover:bg-gray-700
                    transition-colors cursor-pointer
                    ${currentRole === option.key 
                      ? 'bg-blue-50 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400 font-medium' 
                      : 'text-gray-700 dark:text-gray-200'
                    }
                  `}
                >
                  {option.label}
                </button>
              ))}
            </div>
          )}
        </div>
      </EdgeLabelRenderer>
    </>
  )
})

export default ImageRoleEdge
